GetMarkdown = lambda text: (text
    .replace("[", "\[")
    .replace("]", "\]")
    .replace("|", "\|")
    .replace(".", "\.")
    .replace(",", "\,")
    .replace("-", "\-")
    .replace(">", "\>")
    .replace(")", "\)")
    .replace("(", "\(")
    .replace("{", "\{")
    .replace("}", "\}")
    .replace("!", "\!")
)